version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install uv
      - uv pip install --system -r requirements.txt
  build:
    commands:
      - |
        if [ "$RUN_MODE" = "train" ]; then
          python -m src.main run-train
        else
          python -m src.main run
        fi
artifacts:
  files:
    - data/forecast.json
